### ISSUE TITLE
Segmentation fault while mapping

### ISSUE THREAD

**Issue by harisankarsadasivan** [skovaka/UNCALLED#1]
@skovaka The  run_example.sh fails at <uncalled map -x index/example_ref -i ./ >  with a segmentation fault following loading fast5's and mapping.

**Comment by skovaka** [comment]
Sorry about that, should be fixed now. The "-i" option used to accept a directory as input, but now only takes a text file list of fast5s. I've updated the example and README, and have added some error handling so it should check if the input is valid without segfaulting.
