### ISSUE TITLE
Simulator bug?

### ISSUE THREAD

**Issue by dithiii** [skovaka/UNCALLED#11]
When running the simulator, I ran the following command and got the following error:
uncalled sim ../../UNCALLED/example/e.coli.fasta . --ctl-seqsum 20190809_zymo_seqsum.txt --unc-seqsum 20191220_GM12878_seqsum.txt --unc-paf 20191220_GM12878_uncalled.paf --enrich -c 3 --sim-speed 0.25 > uncalled_out.paf 2> uncalled_err.txt

Loading control PAF.............
================================
Procesing run...................
Ordering reads..................
Traceback (most recent call last):
  File "/usr/local/bin/uncalled", line 276, in realtime_cmd
    sim_utils.load_sim(client, conf)
  File "/usr/local/lib/python2.7/dist-packages/uncalled/sim_utils.py", line 387, in load_sim
    odr = np.flip(np.argsort(diff))
TypeError: flip() takes exactly 2 arguments (1 given)

I'm using Linux Mint, fresh install of everything.

**Comment by skovaka** [comment]
That seems to be an issue with your numpy version, which to be fair I did not specify in the README. I just pushed a fix for that specific error, but also specified that in the future we will only officially support python 3.7 and numpy 1.17, which is what is used in the latest MinKNOW release. Hope that helps!

**Comment by skovaka** [comment]
setup.py now automatically checks the numpy version on install (as well as python and pybind11 versions)
