### ISSUE TITLE
How to download raw signal data?

### ISSUE THREAD

**Issue by haowenz** [skovaka/UNCALLED#14]
Hi,

I can only find the fastq files with project number PRJNA604456. Are the raw signal data also available?

Thanks,
Haowen

**Comment by skovaka** [comment]
I had some trouble uploading the raw signal data to SRA, but I will try again this week. If it doesn't work I will upload it somewhere else soon. Sorry about that!

**Comment by skovaka** [comment]
The raw signal data is now available on SRA
