### ISSUE TITLE
Unmapped reads not ejecting

### ISSUE THREAD

**Issue by jkzrich** [skovaka/UNCALLED#16]
Hello,

I started an instance of UNCALLED using the following command:

    uncalled realtime Csojina.fasta --port 8000 -t 8 --enrich -c 3 > uncalled_out_soybeansojina2.paf

When I look at the .paf output, it appears that there are a lot of reads that do not map to the reference, but are not ejected. Example:

    ed2e1457-91b1-4c27-8159-c01f08d39d55	450	*	*	*	*	*	*	*	*	*	255	ch:i:404	   st:i:24150816	qt:f:150.188721	mt:f:8.359437	wt:f:1441.921387	en:f:0.037671
    8eeed2ad-1525-42a5-bff2-132c9f5e9d44	453	*	*	*	*	*	*	*	*	*	255	ch:i:357	st:i:24151447	  qt:f:142.428894	mt:f:7.929103	wt:f:1451.144775	en:f:0.037727
    d3996ea4-37db-4649-b24f-f077ac9081d1	450	*	*	*	*	*	*	*	*	*	255	ch:i:268	st:i:24151338	qt:f:10.439973	mt:f:17.490294	wt:f:1628.886597	en:f:0.046620
    a89bfc35-573d-4073-8cb3-8b04278bcb95	450	*	*	*	*	*	*	*	*	*	255	ch:i:156	st:i:24150719	qt:f:10.750773	mt:f:69.235641	wt:f:1931.648438	en:f:0.070621
    c50db927-83f0-49bf-8f94-2ed193ccbd82	452	*	*	*	*	*	*	*	*	*	255	ch:i:487	st:i:24150905	qt:f:39.190941	mt:f:9.406738

Overall, it seems like roughly .75% of reads are ejected and .25% of reads are kept. But the remaining reads that don't have either designation are still present in the FASTQ files. Am I running the program or interpreting something incorrectly? Thanks for your help!

Jon

**Comment by skovaka** [comment]
Good question! That is probably because those reads end before a decision is made, indicated by the presence "en:i:..." tag at the end of each PAF line. I see the estimated read lengths in your examples are ~450bp, indicating only one chunk was received before a new read was produced by each channel. This shouldn't be a problem, unless the majority of reads have the "en:" tag, which could indicate your read lengths are too short.

**Comment by jkzrich** [comment]
Thanks for your response! That is kind of what I suspected. When I filtered out shorter reads, I did see a significant enrichment of our target. Would you recommend making any chunk size or number changes? When I changed chunk time to 0.4 and number of chunks to 2, it seemed to eject a larger number of reads. Or would this maybe be too stringent?

Thanks for developing this great tool!

**Comment by mschatz** [comment]
Awesome! Glad it is working. Would you be willing to share any of the
details on the target or the level of enrichment? We are very very
interested to hear about how this is working in other labs. We could move
to private email or a quick phone/zoom chat if you would prefer

Thanks!

Mike Schatz

**Comment by jkzrich** [comment]
Hi Mike,

Sure, I'd be happy to have a zoom chat about our results. You can contact me at jrichards@agcenter.lsu.edu

Thanks!
