### ISSUE TITLE
Which port number should I use in `uncalled realtime --port`

### ISSUE THREAD

**Issue by devxia** [skovaka/UNCALLED#17]
Excuse me, what does --port mean in Real-Time ReadUntil here `uncalled realtime E.coli --port 8000 -t 16 --enrich -c 3 > uncalled_out.paf `. Which port number should I choose when I run UNCALLED on my own computer?

**Comment by skovaka** [comment]
The port should be 8000, unless multiple MinIONs have been plugged in since the computer restarted. There used to be a way to list ports if multiple MinIONs were active, but unfortunately that broke with a recent MinKNOW update. The port should always be 800X (e.g. 8001, 8002, ...), so if 8000 doesn't work you can use trial and error until one works. I know this isn't an ideal method, and I'll work on improving it.

If you're having problems running the command before the run starts, see the second paragraph of "Real-Time ReadUntil" section of the README. This is also something I hope to improve.

**Comment by devxia** [comment]
> The port should be 8000, unless multiple MinIONs have been plugged in since the computer restarted. There used to be a way to list ports if multiple MinIONs were active, but unfortunately that broke with a recent MinKNOW update. The port should always be 800X (e.g. 8001, 8002, ...), so if 8000 doesn't work you can use trial and error until one works. I know this isn't an ideal method, and I'll work on improving it.
> 
> If you're having problems running the command before the run starts, see the second paragraph of "Real-Time ReadUntil" section of the README. This is also something I hope to improve.

Thank you very much for your answer to my question, which completely solves my current confusion.

If possible, please allow me to ask another question. 

In one of our attempts, we used the entire human genome as reference, and I referred to the method described in `masking ` to remove repeats. However, when `uncalled index -o hg38 hg38_masked.fa` is executed, after the BWA index is created, the memory usage will slowly expand until it is completely used and an error is reported. Does this mean that the reference genome is too large for current procedures to handle? Thank you!

**Comment by skovaka** [comment]
Yes, the whole human genome is currently too large for UNCALLED to handle. We don't support references larger than 1Gbp yet, but we're working on that.

**Comment by devxia** [comment]
> Yes, the whole human genome is currently too large for UNCALLED to handle. We don't support references larger than 1Gbp yet, but we're working on that.

Thank you very much for answering my question!

**Comment by devxia** [comment]
In fact, When I change my reference and try to use UNCALLED with command `uncalled realtime human_chr --port 8000 -t 16 --deplete -c 10 > uncalled_out.paf`, I got an error like that below:
```
Traceback (most recent call last):
  File "/home/devxia/.local/lib/python3.7/site-packages/uncalled-2.2-py3.7-linux-x86_64.egg/EGG-INFO/scripts/uncalled", line 191, in realtime_cmd
    if not unc.minknow_client.ru_loaded:
AttributeError: module 'uncalled' has no attribute 'minknow_client'
```
I try it before start sequencing and mux scaning both, but stil got this error. Is that mean not install properly? Thank you.

**Comment by skovaka** [comment]
Very sorry, there must have been a git merging issue that caused that problem with realtime mode. I just pushed a fix, please pull from the master branch and try again.
