### ISSUE TITLE
fast5 IO in simulate module

### ISSUE THREAD

**Issue by TorHou** [skovaka/UNCALLED#2]
Hi @skovaka ,

after compilation of this tool I keep having trouble with loading fast5 files. For some reason the filename is not properly passed to the HDF5 loading binary. So when I call the simulate module
```
uncalled simulate --bwa-prefix some/prefix --fast5s some/fast5 --enrich
```
I get this error:
```
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /home/hdftest/snapshots-hdf5_1_10_5/current/src/H5F.c line 509 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: /home/hdftest/snapshots-hdf5_1_10_5/current/src/H5Fint.c line 1498 in H5F_open(): unable to open file: time = Fri Nov 15 17:19:56 2019
', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #002: /home/hdftest/snapshots-hdf5_1_10_5/current/src/H5FD.c line 734 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0FD_sec2_open(): unable to open file: name = '�HDF
    major: File accessibilty
    minor: Unable to open file
Traceback (most recent call last):
  File "./build/scripts-2.7/uncalled", line 510, in <module>
    simulate_cmd(args)
  File "./build/scripts-2.7/uncalled", line 421, in simulate_cmd
    sim.add_fast5s(args.fast5s, args.read_count)
: error in H5FopenDF

```
I have made sure that the fast5 is not corrupted. I get the same error when I use the fast5 from the example directory. I have tried this with a bunch of different installations of HDF5. But in the end I keep getting this error. 
Any idea of what could be the matter here I would really appreciate. 
Best,
Torsten

**Comment by TorHou** [comment]
The fast5 File is supposed to be a text file containing paths to fast5 files .....

**Comment by skovaka** [comment]
Yes, sorry about that, the input used to be more flexible but now only accepts a text file due to refactoring. I've updated the README accordingly.
