### ISSUE TITLE
ModuleNotFoundError: file_read_backwards

### ISSUE THREAD

**Issue by marcus1487** [skovaka/UNCALLED#21]
I have installed uncalled into a new virtual environment using the `pip install git+https://github.com/skovaka/UNCALLED.git` installation method. When I then run `uncalled index` command I get the error text copied at the end of this issue indicating that the `file_read_backwards` module is not found. It looks like the use of the imported function, `FileReadBackwards`, is commented out in `debug.py`. It seems that the `file-read-backwards` package should be added as a dependency in `setup.py` or the import should be removed from `debug.py`.

```
Traceback (most recent call last):
  File "/venv/bin/uncalled", line 35, in <module>
    import uncalled as unc
  File "/venv/lib/python3.7/site-packages/uncalled/__init__.py", line 2, in <module>
    from uncalled import index, pafstats, sim_utils, args, debug, minknow_client
  File "/venv/lib/python3.7/site-packages/uncalled/debug.py", line 8, in <module>
    from file_read_backwards import FileReadBackwards
ModuleNotFoundError: No module named 'file_read_backwards'
```

**Comment by skovaka** [comment]
Sorry about that, I've removed the import statement. Thanks for pointing it out.
