### ISSUE TITLE
CLARIFICATION: What is limiting UNCALLED from being evaluated for r9.4.1?

### ISSUE THREAD

**Issue by harisankarsadasivan** [skovaka/UNCALLED#29]
wouldn't UNCALLED work if the kmer model is replaced with r9.4 (r9.4.1 seems to be unavaialble) and input dataset is from r9.4.1?

**Comment by skovaka** [comment]
UNCALLED works with r9.4.1. The signal characteristics are equivalent to r9.4, and UNCALLED has actually mainly been tested using r9.4.1 data. I'll update the README to reflect that. 

If you have an ONT community account, you can find a slightly more in-depth answer here: https://community.nanoporetech.com/posts/a-minor-revision-to-r9-4-a-2108

**Comment by harisankarsadasivan** [comment]
@skovaka, thanks this helps. One last thing, did you observe 5mer model performs better than 6mer model or were they equivalent for event detection?

**Comment by skovaka** [comment]
They are pretty much equivalent. If you look at the means for 6-mers that have a 5bp suffix/prefix match you'll see they're nearly identical, indicating the 6th base doesn't add much information.

**Comment by harisankarsadasivan** [comment]
Thank you @skovaka
