### ISSUE TITLE
ImportError: libhdf5.so.103: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by nick297** [skovaka/UNCALLED#3]
Hi,
I'm getting this error when trying to run UNCALLED on ubuntu 18.04 on two different machines.
I'm installing HDF5 from source to /usr/local/hdf5 and building first with this command.

```
python3 setup.py build_ext --library-dirs /usr/local/hdf5/lib/ --include-dirs /usr/local/hdf5/include/
sudo python3 setup.py install
```

When I try to run uncalled it gives this error.
```
Traceback (most recent call last):
  File "/usr/local/bin/uncalled", line 25, in <module>
    from uncalled import mapping, index, pafstats
ImportError: libhdf5.so.103: cannot open shared object file: No such file or directory
```

Any help would be appreciated.
Thanks

**Comment by skovaka** [comment]
Hi,

Is `/usr/local/hdf5/lib` in your `$LD_LIBRARY_PATH`? Try running:
```
export LD_LIBRARY_PATH=/usr/local/hdf5/lib:$LD_LIBRARY_PATH
```
And then run UNCALLED. If that works, you should add that line to your ~/.bashrc file to make it persistent.

Hope that helps! Let me know if it works so I can add some clarification to the documentation.

Thanks,
Sam

**Comment by nick297** [comment]
Yep thats fixed it. Thanks!
