### ISSUE TITLE
Question about only the leftmost mapped reads are reported

### ISSUE THREAD

**Issue by twang18** [skovaka/UNCALLED#31]
Hi, thanks for the great work and the comprehensive paper.

I noticed you mentioned "UNCALLED attempts to map a read as early as possible, so the "query end" field corresponds to the leftmost position where UNCALLED was able to confidently map the read. In many cases this may only be 450bp or 900bp into the read", and would like to know if there is any way to report all the mapped and aligned reads using UNCALLED? (e.g. Can I add any arguments or make minor changes on the scripts?)

Your insights or advice is highly appreciated! Thanks!

**Comment by skovaka** [comment]
There isn't currently way to report multiple alignments, or to continue aligning after one confident mapping is found. Just to clarify, would an option to report any alignment longer than Xbp over the full length of the read be helpful? You would also probably want to limit the number and length of gaps in alignments to avoid chaining random false positives together, which would be more likely to occur when considering entire reads.

**Comment by twang18** [comment]
Hi Skovaka, thanks very much for the clarification. I can fully understand your point now.
