### ISSUE TITLE
Minimum hardware requirements

### ISSUE THREAD

**Issue by snystrom** [skovaka/UNCALLED#36]
Hi, I noticed in the Uncalled manuscript a rather beefy machine was used for the sequencing. I was curious whether someone could comment on the minimum hardware specs to run this with good performance. For instance, would a computer with the minimum specs for a MinION (ie 16GB RAM, >4 core CPU, ~1TB SSD) be sufficient to run this in real time? If not, what should be modified?

Cheers.

**Comment by skovaka** [comment]
Your specs should be sufficient, although more CPU power might improve the level of enrichment. Performance is really sample- and flowcell-dependent, so it's hard to predict how many cores would be ideal. In general more is better, but running with 8 threads on 4 cores should work fairly well. I'd also make sure you have at least 500GB of free disk space for your run.

**Comment by snystrom** [comment]
Great, thanks! 

> Performance is really sample- and flowcell-dependent

I did have another question related to this. Is there a reason this won't work for r10 flowcells? Or is it just untested? Are there plans to support them moving forward?

**Comment by skovaka** [comment]
r10 flowcells have very different signal characteristics than r9.4. The biggest challenge is that r10 pores cover more bases than r9.4, meaning our pore model would probably need longer k-mers, and it would take some work to efficiently handle that. We may work on it someday, but don't have any immediate plans.

**Comment by snystrom** [comment]
Got it. Thanks for the help!

At the very least, I'll go ahead an express interest in supporting r10 pores if it helps convince someone to fund the work! 😄
