### ISSUE TITLE
Error when running uncalled map

### ISSUE THREAD

**Issue by ncolaian** [skovaka/UNCALLED#38]
Hi,

I am currently getting an error when trying to run uncalled map.

```uncalled map nif_data/NifH_data/uncalled_cdhit_ref/5k_nifH nanopore_data/single_fast5/0/8384d558-af58-4306-b661-34ed2ec7e3b7.fast5```

Loading fast5s
Mapping
HDF5-DIAG: Error detected in HDF5 (1.8.21) thread 140484998567744:
  #000: H5Dio.c line 223 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5Dio.c line 605 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: H5Dchunk.c line 2093 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: H5Dchunk.c line 3123 in H5D__chunk_lock(): data pipeline read failed
    major: Data filters
    minor: Filter operation failed
  #004: H5Z.c line 1311 in H5Z_pipeline(): required filter 'vbz' is not registered
    major: Data filters
    minor: Read failed
  #005: H5PL.c line 380 in H5PL_load(): search in paths failed
    major: Plugin for dynamically loaded library
    minor: Can't get value
  #006: H5PL.c line 738 in H5PL__find(): can't open directory: /usr/local/hdf5/lib/plugin
    major: Plugin for dynamically loaded library
    minor: Can't open directory or file
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/uncalled", line 341, in <module>
    map_cmd(conf, args)
  File "/home/ubuntu/.local/bin/uncalled", line 157, in map_cmd
    for p in mapper.update():
RuntimeError: /Raw/Reads/Read_137128/Signal: error in H5Dread
terminate called without an active exception
Aborted (core dumped)

Here is the file version:
HDF5 "8384d558-af58-4306-b661-34ed2ec7e3b7.fast5" {
ATTRIBUTE "file_version" {
   DATATYPE  H5T_IEEE_F64LE
   DATASPACE  SCALAR
   DATA {
   (0): 2
   }
}
}

and the listing of the fast5 groups

/                        Group
/Analyses                Group
/Analyses/Basecall_1D_000 Group
/Analyses/Basecall_1D_000/BaseCalled_template Group
/Analyses/Basecall_1D_000/BaseCalled_template/Fastq Dataset {SCALAR}
/Analyses/Basecall_1D_000/Summary Group
/Analyses/Basecall_1D_000/Summary/basecall_1d_template Group
/Analyses/Segmentation_000 Group
/Analyses/Segmentation_000/Summary Group
/Analyses/Segmentation_000/Summary/segmentation Group
/Raw                     Group
/Raw/Reads               Group
/Raw/Reads/Read_137128   Group
/Raw/Reads/Read_137128/Signal Dataset {14750/Inf}
/UniqueGlobalKey         Group
/UniqueGlobalKey/channel_id Group
/UniqueGlobalKey/context_tags Group
/UniqueGlobalKey/tracking_id Group

Do you have any ideas why this may be failing? 

Thanks!

**Comment by skovaka** [comment]
Try installing the VBZ compression plugin: https://github.com/nanoporetech/vbz_compression
ONT recently changed their compression format, which didn't cause any problems when I tested it, but it looks like you might need to install it manually. Let me know if that works and I'll working on automating that, or at least add a note to the readme

**Comment by ncolaian** [comment]
Thanks for the quick response! 

Unfortunately this didn't work for me. I am still getting the same error. I'm thinking that maybe it has to do with my file, however I'm not sure what's the hang-up. 

Would you mind quickly testing or looking at this file? It is from a multi-read-fast5 file where I split it into single read files. The multi read file was downloaded from the pass directory saved by the Mk1C nanopore. 

Thanks

https://pivotbio-my.sharepoint.com/:u:/p/ncolaianni/EfXpVVzJBq9BqHl9a0GQcXoB1Xf1ICBeUVybiGDYT1P4kQ?e=PeFWJC

**Comment by skovaka** [comment]
Thanks for sharing! Looks like it's the same issue reported here: https://github.com/nanoporetech/vbz_compression/issues/5
If you're on Linux (and maybe Mac too) try running `export HDF5_PLUGIN_PATH=/usr/local/hdf5/lib/plugin`, then run `uncalled map`. 
"/usr/local/hdf5/lib/plugin" should contain a file called "libvbz_hdf_plugin.so". If that command doesn't work and you don't see that file, you'll need to figure out where the VBZ installer put the plugin library. Hope that helps!

**Comment by ncolaian** [comment]
Ah, the last piece! It worked like a charm. Thanks a lot!

**Comment by skovaka** [comment]
No problem, glad it worked!
