### ISSUE TITLE
Trouble indexing fasta-file.

### ISSUE THREAD

**Issue by JudoWill** [skovaka/UNCALLED#5]
Hi all! I'm trying to get `uncalled` installed and setup.

I am getting the following error and I'm not sure if it is my numpy version (currently using 1.18.1) or something else.

```
uncalled index -i HIV1_FLT_2016_genome_DNA.fa -x HIV1_index
Initializing parameter search
Writing default parameters
Traceback (most recent call last):
  File "/home/will/anaconda/envs/nanoporetest/bin/uncalled", line 534, in <module>
    index_cmd(args)
  File "/home/will/anaconda/envs/nanoporetest/bin/uncalled", line 154, in index_cmd
    p.add_preset("default", tgt_speed=115)
  File "/home/will/anaconda/envs/nanoporetest/lib/python3.7/site-packages/uncalled/index.py", line 134, in add_preset
    delta = self.get_fn_speed(fn_locs, fn_pcks) - tgt_speed
  File "/home/will/anaconda/envs/nanoporetest/lib/python3.7/site-packages/uncalled/index.py", line 113, in get_fn_speed
    pcks = np.interp(self.all_locs, fn_locs, fn_pcks)
  File "<__array_function__ internals>", line 6, in interp
  File "/home/will/anaconda/envs/nanoporetest/lib/python3.7/site-packages/numpy/lib/function_base.py", line 1412, in interp
    return interp_func(x, xp, fp, left, right)
TypeError: Cannot cast array data from dtype('O') to dtype('float64') according to the rule 'safe'
```

Or is there some requirement about the reference file that's not documented?

It seems `numpy` is required, at least, for indexing yet it is not marked as a requirement. Can you pin a specific `numpy` version in a requirements file?

**Comment by skovaka** [comment]
Hello,

I don't think this is a numpy version issue, although you're right I should
add that as a dependency. What is the size of the reference you're trying
to index? Would it be possible for you to share it with me? I designed the
indexing procedure for non-repetitive megabase-scale references, and it's
possible going outside that range (too small, too large, too repetitive)
could cause problems like this. Hopefully it will only require some small
adjustments. I've been meaning to explore this further, so any additional
info you could provide would be helpful.

Thanks,
Sam

**Comment by JudoWill** [comment]
Hmmm, maybe. Here's a link to the "genome" I'm trying to index.
https://www.dropbox.com/s/5imwr5brjj52jdh/HIV1_FLT_2016_genome_DNA.fa?dl=0

Basically we're trying to use `uncalled` to enrich for sequences containing HIV. But HIV is highly variable and some patients will vary by 10% in some locations which can throw off mappers. So, I concatenated a collection of HIV genomes into one file and built the index. I've used this strategy for BioBloom and other kmer matching tools with great success.

There are no "repetitive" sections. Each genome does have two copies of one ~600bp Long Terminal Repeat (one at each end). The genomes are short by your standards, only 9700bp each. Based on your suggestion I also tried to build the index with a single reference genome, got the same error. I also tried one where I removed the duplicated region, same error.

**Comment by skovaka** [comment]
Thanks for letting me see the references. I had never tried running UNCALLED with viral genomes, but as I suspected the small size seems be causing problems. I pick reference parameters based on metrics related to repeat content, but it seems like for genomes < 1Mbp I don't have things calibrated right. I've figured out for a single HIV genome you can add the option `--max-replen 90` to `uncalled index`. This makes it ignore repeats over length 90bp, which fixes the error for one genome.

Unfortunately, UNCALLED will not work if you combine many similar references. This essentially introduces many repeats in all the conserved regions. You could try including a small number of very divergent strains, or try including one "representative" genome and add some segments of variable regions, but no guarantees that this will work.

I plan to work on both of these issues in the future. In the short term I plan to make indexing work better for smaller references soon, and I should add more meaningful error messages for references that don't work. I will leave this issue open until I do that. The problem with collections of highly similar genomes will probably be a longer term issue to work on.

**Comment by JudoWill** [comment]
Thanks for the help. I can confirm that the index did build when I used a single representative genome and `--max-replen 90`. I was able to the use `uncalled map` to identify my HIV containing reads with about 98% accuracy using `pafstats`. 


They were only reads from a nearly identical reference genome. I'm trying to think about capturing the variation. In your bioArxiv paper and Github you have a masking protocol to mask repetitive k-mers. Since you've looked at the genomes do you see any problem using the `mask_internal` to remove identical k-mers across strains and then used `mask_external` to remove k-mers associated with the background human DNA? Do you think your standard guess of a 10-mer makes sense?

**Comment by skovaka** [comment]
Glad the single genome works! Yes, those scripts are a good starting place,
and 10-mers do seem to be optimal based on my human gene panel tests. I'm
actively working on more automated masking methods, and ideally trying to
make them unnecissary in the future, so keep an eye out for that. I hope
the scripts help for now.

Thanks,
Sam

**Comment by skovaka** [comment]
I just committed a new version which should fix the error. It should now be able to index any reference, although the mapping rate on repetitive references, particularly small references, will likely still be pretty bad. Besides messing with the masking scripts, I would recommend removing one copy of the long terminal repeats in each genome. This will make it difficult to map reads which span the border of the removed copy, but I think it will be worth it because otherwise > 5% of your reference is an exact repeat. Let me know if you have any further issues.
