### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by JacobJanzen** [skovaka/UNCALLED#56]
Would it be possible to make a new release for this? We ran into [this](https://github.com/skovaka/UNCALLED/issues/54) issue at my organization recently because we were using the v2.2 tag which is the latest tag on the repository, but that tag is 2 years old. It would be really nice to have a newer pinned version so that we don't have to choose between an old version and the current contents of the master branch.

**Comment by skovaka** [comment]
Good idea! Just tagged the latest version as v2.3

**Comment by jjanzenn** [comment]
Thanks!
