### ISSUE TITLE
support for python 3.7

### ISSUE THREAD

**Issue by HenrivdGeest** [skovaka/UNCALLED#7]
The new upcoming Minknow software release version 20.03 will work with python 3.7. Does uncalled still works with this new Python? Or does it means that uncalled runs on python2 and minknow on python3?

**Comment by skovaka** [comment]
It should work with python 3.7. "uncalled map" definitely does, but I will test the realtime mode once the update is out. The python2 compatibility was only so it would work with MinKNOW, I mainly develop it using python3. Thanks for bringing this to my attention!
